//! IEEE 1800-2023 clause 16: assertions.

use crate::harness::{Order, check};

// §16.10: assertion local variables
#[test]
fn c16_10_assertion_local_variables() {
    check(
        "c16_local",
        include_str!("sv/c16_local.sv"),
        "c16_local",
        Order::Exact,
        &[
            "T|16.14.6|inf P t=25",
            "T|16.10|P t=35",
            "T|16.10|cnt cover t=35",
            "T|16.8|arg P t=35",
            "T|16.14.6|inf P t=55",
            "T|16.10|cnt cover t=65",
            "T|16.8|arg P t=65",
            "T|16.10|F t=75",
        ],
        &[],
    );
}

// §16.10: Local variables in sequences/properties
#[test]
fn c16_10_local_variables() {
    check(
        "16.10_local_variables",
        include_str!("sv/16.10_local_variables.sv"),
        "t16_10",
        Order::Exact,
        &["T|lv|P t=35", "T|lv|F t=85"],
        &[],
    );
}

// §16.11: Calling subroutines on a sequence match `(a, f())`
#[test]
fn c16_11_subroutine_on_match() {
    check(
        "16.11_subroutine_on_match",
        include_str!("sv/16.11_subroutine_on_match.sv"),
        "t16_11",
        Order::Exact,
        &["T|m|match a t=15", "T|m|match b t=25"],
        &[],
    );
}

// §16.12.8, §16.12.12: iff
#[test]
fn c16_12_12_until() {
    // Known gap (§16.12.12): `until` reference `P t=45`, xezim `P t=25`
    // Known gap (§16.12.12): `s_until` reference `P t=45`, xezim `P t=25`
    // Known gap (§16.12.8): `iff`: xezim prints extra 5 lines
    check(
        "16.12.12_until",
        include_str!("sv/16.12.12_until.sv"),
        "t16_12",
        Order::Exact,
        &["T|iff|F t=15", "T|iff|F t=25", "T|iff|F t=35"],
        &[
            "T|until|",
            "T|s_until|",
            "T|iff|F t=5",
            "T|iff|F t=45",
            "T|iff|F t=55",
            "T|iff|F t=65",
            "T|iff|F t=75",
        ],
    );
}

// §16.6, §16.12.4, §16.12.5, §16.12.15: property operators, followed-by, $onehot/$isunknown
#[test]
fn c16_12_property_operators() {
    // Known gap (§16.12): `b[+]`, `nexttime [n]`, `eventually [m:n]`, `s_eventually [m:n]`, `s_always [m:n]`,
    // `until_with`, `accept_on`/`reject_on` (and sync_), `#-#` and `#=#` do not parse; those
    // assertions are commented out (XZFAIL) and their reference lines left out.
    // Known gap (§16.12.12): `q_suntil`: 5 reference lines differ from xezim's 5, e.g. reference `P t=35`, xezim `P t=25`
    // Known gap (§16.9.2): `q_repstar` reference `P t=105`, xezim `P t=205`
    // Assertions that complete in the same time step report from separate processes; IEEE 1800 §4.7 leaves their order open.
    check(
        "c16_seq2_xzok",
        include_str!("sv/c16_seq2_xzok.sv"),
        "c16_seq2",
        Order::Multiset,
        &[
            "T|q_not_prop|F t=5",
            "T|q_isunk|P t=5",
            "T|q_or_prop|F t=15",
            "T|q_onehot|P t=15",
            "T|q_isunk|P t=15",
            "T|q_snext|P t=25",
            "T|q_or_prop|P t=25",
            "T|q_and_prop|F t=25",
            "T|q_not_prop|F t=25",
            "T|q_isunk|P t=25",
            "T|q_weak|P t=35",
            "T|q_weak|P t=35",
            "T|q_strong|P t=35",
            "T|q_strong|P t=35",
            "T|q_snext|P t=35",
            "T|q_plus|P t=35",
            "T|q_plus|P t=35",
            "T|q_and_prop|P t=35",
            "T|q_and_prop|P t=35",
            "T|q_seq_and_len|P t=35",
            "T|q_star|P t=35",
            "T|q_star|P t=35",
            "T|q_onehot|F t=35",
            "T|q_ended_prop|P t=35",
            "T|q_ended_prop|P t=35",
            "T|q_not_prop|F t=35",
            "T|q_not_prop|P t=35",
            "T|q_isunk|P t=35",
            "T|q_seq_and_len|P t=45",
            "T|q_repstar|P t=45",
            "T|q_repstar|P t=45",
            "T|q_not_prop|F t=45",
            "T|q_isunk|P t=45",
            "T|q_or_prop|F t=55",
            "T|q_onehot|P t=55",
            "T|q_isunk|P t=55",
            "T|q_suntil|F t=65",
            "T|q_snext|F t=65",
            "T|q_and_prop|F t=65",
            "T|q_seq_and_len|F t=65",
            "T|q_not_prop|F t=65",
            "T|q_not_prop|P t=65",
            "T|q_isunk|P t=65",
            "T|q_weak|F t=75",
            "T|q_onehot|P t=75",
            "T|q_strong|F t=75",
            "T|q_and_prop|P t=75",
            "T|q_not_prop|F t=75",
            "T|q_isunk|P t=75",
            "T|q_or_prop|F t=85",
            "T|q_onehot|P t=85",
            "T|q_ended_prop|F t=85",
            "T|q_isunk|P t=85",
            "T|q_snext|P t=95",
            "T|q_or_prop|P t=95",
            "T|q_and_prop|F t=95",
            "T|q_not_prop|F t=95",
            "T|q_isunk|P t=95",
            "T|q_onehot|F t=105",
            "T|q_snext|F t=105",
            "T|q_strong|P t=105",
            "T|q_strong|P t=105",
            "T|q_weak|P t=105",
            "T|q_weak|P t=105",
            "T|q_or_prop|P t=105",
            "T|q_seq_and_len|F t=105",
            "T|q_seq_and_len|P t=105",
            "T|q_and_prop|P t=105",
            "T|q_plus|P t=105",
            "T|q_plus|P t=105",
            "T|q_plus|P t=105",
            "T|q_star|P t=105",
            "T|q_star|P t=105",
            "T|q_star|P t=105",
            "T|q_star|P t=105",
            "T|q_ended_prop|P t=105",
            "T|q_ended_prop|P t=105",
            "T|q_not_prop|F t=105",
            "T|q_isunk|P t=105",
            "T|q_seq_and_len|F t=115",
            "T|q_suntil|F t=115",
            "T|q_and_prop|F t=115",
            "T|q_snext|F t=115",
            "T|q_not_prop|F t=115",
            "T|q_not_prop|P t=115",
            "T|q_isunk|P t=115",
            "T|q_or_prop|F t=125",
            "T|q_onehot|P t=125",
            "T|q_weak|F t=125",
            "T|q_strong|F t=125",
            "T|q_ended_prop|F t=125",
            "T|q_isunk|P t=125",
            "T|q_snext|P t=135",
            "T|q_and_prop|P t=135",
            "T|q_and_prop|F t=135",
            "T|q_onehot|P t=135",
            "T|q_not_prop|F t=135",
            "T|q_not_prop|P t=135",
            "T|q_isunk|P t=135",
            "T|q_and_prop|P t=145",
            "T|q_seq_and_len|F t=145",
            "T|q_onehot|P t=145",
            "T|q_weak|F t=145",
            "T|q_strong|F t=145",
            "T|q_not_prop|F t=145",
            "T|q_isunk|P t=145",
            "T|q_plus|P t=155",
            "T|q_plus|P t=155",
            "T|q_repstar|P t=155",
            "T|q_star|P t=155",
            "T|q_ended_prop|P t=155",
            "T|q_not_prop|F t=155",
            "T|q_isunk|P t=155",
            "T|q_or_prop|F t=165",
            "T|q_onehot|P t=165",
            "T|q_isunk|P t=165",
            "T|q_snext|F t=175",
            "T|q_suntil|F t=175",
            "T|q_or_prop|F t=175",
            "T|q_and_prop|F t=175",
            "T|q_seq_and_len|F t=175",
            "T|q_onehot|P t=175",
            "T|q_not_prop|F t=175",
            "T|q_isunk|P t=175",
            "T|q_snext|P t=185",
            "T|q_strong|F t=185",
            "T|q_weak|F t=185",
            "T|q_or_prop|P t=185",
            "T|q_and_prop|F t=185",
            "T|q_not_prop|F t=185",
            "T|q_isunk|P t=185",
            "T|q_weak|F t=195",
            "T|q_strong|F t=195",
            "T|q_and_prop|F t=195",
            "T|q_seq_and_len|F t=195",
            "T|q_seq_and_len|F t=195",
            "T|q_snext|F t=195",
            "T|q_ended_prop|F t=195",
            "T|q_ended_prop|F t=195",
            "T|q_not_prop|F t=195",
            "T|q_not_prop|P t=195",
            "T|q_isunk|P t=195",
            "T|q_strong|P t=205",
            "T|q_weak|P t=205",
            "T|q_onehot|F t=205",
            "T|q_and_prop|P t=205",
            "T|q_plus|P t=205",
            "T|q_plus|P t=205",
            "T|q_plus|P t=205",
            "T|q_star|P t=205",
            "T|q_star|P t=205",
            "T|q_star|P t=205",
            "T|q_not_prop|F t=205",
            "T|q_isunk|P t=205",
            "T|q_or_prop|F t=215",
            "T|q_onehot|P t=215",
            "T|q_ended_prop|F t=215",
            "T|q_isunk|P t=215",
            "T|q_snext|P t=225",
            "T|q_onehot|P t=225",
            "T|q_and_prop|P t=225",
            "T|q_and_prop|F t=225",
            "T|q_not_prop|F t=225",
            "T|q_not_prop|P t=225",
            "T|q_isunk|P t=225",
            "T|q_seq_and_len|P t=235",
            "T|q_repstar|P t=235",
            "T|q_weak|P t=235",
            "T|q_strong|P t=235",
            "T|q_ended_prop|P t=235",
            "T|q_plus|P t=235",
            "T|q_star|P t=235",
            "T|q_not_prop|F t=235",
            "T|q_isunk|P t=235",
            "T|q_not_prop|F t=245",
            "T|q_isunk|P t=245",
            "T|q_not_prop|F t=255",
            "T|q_isunk|P t=255",
            "T|q_not_prop|F t=265",
            "T|q_isunk|P t=265",
            "T|q_not_prop|F t=275",
            "T|q_isunk|P t=275",
            "T|q_not_prop|F t=285",
            "T|q_isunk|P t=285",
            "T|q_not_prop|F t=295",
            "T|q_isunk|P t=295",
            "T|q_not_prop|F t=305",
            "T|q_isunk|P t=305",
            "T|q_not_prop|F t=315",
            "T|q_isunk|P t=315",
            "T|q_not_prop|F t=325",
            "T|q_isunk|P t=325",
        ],
        &[
            "T|q_suntil|P t=35",
            "T|q_suntil|P t=25",
            "T|q_suntil|P t=105",
            "T|q_suntil|P t=95",
            "T|q_suntil|P t=155",
            "T|q_suntil|P t=135",
            "T|q_suntil|F t=195",
            "T|q_suntil|P t=185",
            "T|q_suntil|P t=2",
            "T|q_repstar|P t=105",
            "T|q_repstar|P t=205",
        ],
    );
}

// §16.14.2, §16.14.4, §16.17: multiclock sequences and properties
#[test]
fn c16_13_multiclock() {
    // Known gap (§16.13): `16.13`: 2 reference lines differ from xezim's 3, e.g. reference `mc1 F t=21`, xezim `mc1 F t=25`
    // Assertions that complete in the same time step report from separate processes; IEEE 1800 §4.7 leaves their order open.
    check(
        "c16_multi",
        include_str!("sv/c16_multi.sv"),
        "c16_multi",
        Order::Multiset,
        &[
            "T|16.13|mc2 F t=5",
            "T|16.14.3|cover seq t=25",
            "T|16.17|expect P t=35",
            "T|16.17|after expect t=35",
            "T|16.13|mc2 F t=35",
            "T|16.13|mc2 F t=45",
            "T|16.13|mc2 F t=55",
            "T|16.13|mc2 F t=65",
            "T|16.13|mc2 F t=75",
            "T|16.13|mc2 F t=85",
            "T|16.13|mc1 F t=105",
            "T|16.13|mc2 F t=105",
            "T|16.14.3|cover seq t=105",
            "T|16.13|mc2 F t=105",
            "T|16.13|mc2 F t=115",
            "T|16.13|mc2 F t=125",
            "T|16.13|mc2 F t=135",
            "T|16.13|mc2 F t=145",
        ],
        &[
            "T|16.13|mc1 F t=2",
            "T|16.13|mc2 F t=21",
            "T|16.13|mc2 F t=25",
            "T|16.13|mc2 F t=155",
        ],
    );
}

// §16.13: Multiclock sequences/properties (clock flow to next clock)
#[test]
fn c16_13_multiclock_next_clock() {
    // Known gap (§16.13): `mc1` reference `F t=21`, xezim `F t=25`
    // Known gap (§16.13): `mc2`: 1 reference lines differ from xezim's 2, e.g. reference `F t=21`, xezim `F t=25`
    check(
        "16.13_multiclock_next_clock",
        include_str!("sv/16.13_multiclock_next_clock.sv"),
        "t16_13",
        Order::Exact,
        &[
            "T|mc2|F t=5",
            "T|mc2|F t=35",
            "T|mc2|F t=45",
            "T|mc2|F t=55",
        ],
        &["T|mc1|", "T|mc2|F t=21", "T|mc2|F t=25", "T|mc2|F t=65"],
    );
}

// §16.14.6: Embedding concurrent assertions in procedural code (enabling condition, inferred clock)
#[test]
fn c16_14_6_procedural_assert_gating() {
    check(
        "16.14.6_procedural_assert_gating",
        include_str!("sv/16.14.6_procedural_assert_gating.sv"),
        "t16_14",
        Order::Exact,
        &["T|inf|P t=35"],
        &[],
    );
}

// §16.15: Disable iff resolution: default disable iff
#[test]
fn c16_15_default_disable_iff() {
    check(
        "16.15_default_disable_iff",
        include_str!("sv/16.15_default_disable_iff.sv"),
        "t16_15",
        Order::Exact,
        &[],
        &[],
    );
}

// §16.3: Immediate/deferred assertions inside always_comb / always @*
#[test]
fn c16_3_always_comb_assert_not_rerun() {
    // Known gap (§16.3): `i`: xezim prints extra 3 lines
    // Known gap (§16.4): `s`: xezim prints extra `FAIL a=0 b=1 t=4`
    // The immediate and deferred assertions report from separate processes in the same time step; IEEE 1800 §4.7 leaves their order open.
    check(
        "16.3_always_comb_assert_not_rerun",
        include_str!("sv/16.3_always_comb_assert_not_rerun.sv"),
        "t16_3b",
        Order::Multiset,
        &[
            "T|i|pass a=0 b=0 t=0",
            "T|f|pass a=0 b=0 t=0",
            "T|i|pass a=2 b=1 t=1",
            "T|f|pass a=2 b=1 t=1",
            "T|i|pass a=3 b=3 t=2",
            "T|f|pass a=3 b=3 t=2",
            "T|i|FAIL a=1 b=3 t=3",
            "T|s|FAIL a=1 b=3 t=3",
            "T|i|pass a=1 b=1 t=3",
            "T|f|pass a=1 b=1 t=3",
            "T|i|FAIL a=0 b=5 t=4",
            "T|s|FAIL a=0 b=5 t=4",
            "T|f|FAIL a=0 b=5 t=4",
        ],
        &[
            "T|i|pass a=2 b=0 t=1",
            "T|i|pass a=3 b=1 t=2",
            "T|i|FAIL a=0 b=1 t=4",
            "T|s|FAIL a=0 b=1 t=4",
        ],
    );
}

// §16.3: immediate and deferred assertions
#[test]
fn c16_3_immediate_assertions() {
    // Known gap (§20.12): `20.12`: xezim prints extra `BAD s5 not off`
    check(
        "c16_imm",
        include_str!("sv/c16_imm.sv"),
        "c16_imm",
        Order::Exact,
        &[
            "T|16.3|pass action",
            "T|16.3|fail action c16_imm.s2",
            "T|16.3|x fails",
            "T|16.3|z fails",
            "T|16.3|cover pass",
            "T|16.4|final pass a=1 t=0",
            "T|16.4|final pass a=6 t=1",
            "T|16.4|final pass a=3 t=2",
            "T|16.3|default severity follows",
            "T|20.12|s5b fires",
            "T|16.4|final pass a=9 t=4",
        ],
        &["T|20.12|BAD s5 not off"],
    );
}

// §16.3: Immediate assertions: failure with no else clause shall call $error
#[test]
fn c16_3_no_else_default_error() {
    check(
        "16.3_no_else_default_error",
        include_str!("sv/16.3_no_else_default_error.sv"),
        "t16_3",
        Order::Exact,
        &["T|a|done"],
        &[],
    );
}

// §16.9.3: $past(expr, n, gating_expr)
#[test]
fn c16_9_3_past_gating() {
    // Known gap (§16.9.3): `p`: 2 reference lines differ from xezim's 2, e.g. reference `t=45 v=3 past=2 past_gated=1`, xezim `t=45 v=3 past=2 past_gated=2`
    check(
        "16.9.3_past_gating",
        include_str!("sv/16.9.3_past_gating.sv"),
        "t16_9b",
        Order::Exact,
        &[
            "T|p|t=5 v=0 past=0 past_gated=0",
            "T|p|t=15 v=0 past=0 past_gated=0",
            "T|p|t=25 v=1 past=0 past_gated=0",
            "T|p|t=35 v=2 past=1 past_gated=1",
        ],
        &[
            "T|p|t=45 v=3 past=2 past_gated=",
            "T|p|t=55 v=4 past=3 past_gated=",
        ],
    );
}

// §16.9.3: sampled value functions and global clocking functions
#[test]
fn c16_9_3_sampled_value_functions() {
    // Known gap (§16.9.3): `16.9.3`: 4 reference lines differ from xezim's 4, e.g. reference `t=15 v=0 past=0 past2=x pastE=x rose=0 fell=0 stable=1 changed=0 lr...`, xezim `t=15 v=0 past=0 past2=x pastE=0 rose=0 fell=0 stable=1 changed=0 lr...`
    // Known gap (§16.9.4): `16.9.4`: 5 reference lines differ from xezim's 5, e.g. reference `t=15 rose_gclk=0 stable_gclk=1 future_gclk=0`, xezim `t=15 rose_gclk=0 stable_gclk=0 future_gclk=0`
    check(
        "c16_sampled",
        include_str!("sv/c16_sampled.sv"),
        "c16_sampled",
        Order::Exact,
        &[
            "T|16.9.3|t=5 v=0 past=x past2=x pastE=x rose=0 fell=0 stable=0 changed=1 lrose=0 lfell=0 lstab=1",
            "T|16.9.4|t=5 rose_gclk=0 stable_gclk=0 future_gclk=0",
            "T|16.9.3|t=35 v=1 past=1 past2=0 pastE=1 rose=0 fell=0 stable=1 changed=0 lrose=1 lfell=0 lstab=0",
            "T|16.9.3|t=45 v=3 past=1 past2=1 pastE=1 rose=0 fell=1 stable=0 changed=1 lrose=0 lfell=0 lstab=0",
            "T|16.9.4|t=45 rose_gclk=0 stable_gclk=0 future_gclk=0",
            "T|16.9.4|t=55 rose_gclk=0 stable_gclk=0 future_gclk=0",
            "T|16.9.3|past-fail t=65",
            "T|16.9.3|t=75 v=2 past=2 past2=x pastE=2 rose=0 fell=0 stable=1 changed=0 lrose=0 lfell=0 lstab=1",
        ],
        &[
            "T|16.9.3|t=15 v=0 past=0 past2=x pastE=",
            "T|16.9.3|t=25 v=1 past=0 past2=0 pastE=",
            "T|16.9.3|t=55 v=x past=3 past2=1 pastE=",
            "T|16.9.3|t=65 v=2 past=x past2=3 pastE=",
            "T|16.9.4|t=15 rose_gclk=0 stable_gclk=",
            "T|16.9.4|t=25 rose_gclk=",
            "T|16.9.4|t=35 rose_gclk=0 stable_gclk=",
            "T|16.9.4|t=65 rose_gclk=",
            "T|16.9.4|t=75 rose_gclk=0 stable_gclk=",
        ],
    );
}

// §16.5, §16.9.2, §16.9.5, §16.9.6, §16.9.7, §16.9.8, ...: sequence and property operators
#[test]
fn c16_9_sequence_operators() {
    // Known gap (§16.12): `s_until_with`, `always [m:n]`, `implies` and property `case` do not parse;
    // those assertions are commented out (XZFAIL) and their reference lines left out.
    // Known gap (§16.12.8): `p_iff`: 19 reference lines differ from xezim's 19, e.g. reference `P t=5`, xezim `F t=5`
    // Known gap (§16.12.12): `p_until`: 5 reference lines differ from xezim's 5, e.g. reference `P t=35`, xezim `P t=25`
    // Known gap (§16.9.2): `p_zero_rep` reference `P t=105`, xezim `P t=205`
    // Assertions that complete in the same time step report from separate processes; IEEE 1800 §4.7 leaves their order open.
    check(
        "c16_seq_xzok",
        include_str!("sv/c16_seq_xzok.sv"),
        "c16_seq",
        Order::Multiset,
        &[
            "T|p_rep_range|F t=5",
            "T|p_and|F t=5",
            "T|p_not|P t=5",
            "T|p_impl_ov|F t=15",
            "T|p_intersect|F t=15",
            "T|p_iff|F t=15",
            "T|p_impl_ov|P t=25",
            "T|p_impl_nov|F t=25",
            "T|p_or|P t=25",
            "T|p_ifelse|P t=25",
            "T|p_next|P t=25",
            "T|p_disable|F t=25",
            "T|cov1|C t=25",
            "T|p_not|F t=25",
            "T|p_ifelse|P t=35",
            "T|p_fm|P t=35",
            "T|p_fm|P t=35",
            "T|p_throughout|P t=35",
            "T|p_next|P t=35",
            "T|p_intersect|P t=35",
            "T|p_or|P t=35",
            "T|p_nonc|F t=35",
            "T|p_zero_rep|P t=35",
            "T|p_range|P t=35",
            "T|p_range|P t=35",
            "T|p_disable|P t=35",
            "T|p_delay2|P t=35",
            "T|p_impl_nov|P t=35",
            "T|cov1|C t=35",
            "T|cov2|C t=35",
            "T|cov2|C t=35",
            "T|p_rep_range|F t=35",
            "T|p_rep_range|P t=35",
            "T|p_and|F t=35",
            "T|p_and|P t=35",
            "T|p_not|P t=35",
            "T|p_not|P t=35",
            "T|p_iff|F t=35",
            "T|p_zero_rep|P t=45",
            "T|p_goto|F t=45",
            "T|p_goto|F t=45",
            "T|p_throughout|P t=45",
            "T|p_delay2|P t=45",
            "T|p_rep|P t=45",
            "T|p_rep_range|F t=45",
            "T|p_rep_range|P t=45",
            "T|p_and|F t=45",
            "T|p_and|P t=45",
            "T|p_not|P t=45",
            "T|p_impl_ov|F t=55",
            "T|p_intersect|F t=55",
            "T|p_nonc|P t=55",
            "T|p_within|P t=55",
            "T|p_within|P t=55",
            "T|p_until|F t=65",
            "T|p_ifelse|P t=65",
            "T|p_next|F t=65",
            "T|p_disable|F t=65",
            "T|p_impl_nov|F t=65",
            "T|p_rep_range|F t=65",
            "T|p_rep_range|F t=65",
            "T|p_and|F t=65",
            "T|p_and|F t=65",
            "T|p_not|P t=65",
            "T|p_not|P t=65",
            "T|p_throughout|F t=75",
            "T|p_or|F t=75",
            "T|p_delay2|F t=75",
            "T|p_rep_range|F t=75",
            "T|p_and|F t=75",
            "T|p_not|P t=75",
            "T|p_iff|F t=75",
            "T|p_intersect|F t=85",
            "T|p_range|F t=85",
            "T|p_fm|F t=85",
            "T|p_impl_ov|F t=85",
            "T|p_nonc|P t=85",
            "T|p_iff|F t=85",
            "T|p_impl_nov|F t=95",
            "T|p_or|P t=95",
            "T|p_ifelse|P t=95",
            "T|p_next|P t=95",
            "T|p_disable|F t=95",
            "T|cov1|C t=95",
            "T|p_impl_ov|P t=95",
            "T|p_within|F t=95",
            "T|p_not|F t=95",
            "T|p_impl_nov|P t=105",
            "T|p_delay2|P t=105",
            "T|p_intersect|F t=105",
            "T|p_intersect|F t=105",
            "T|p_throughout|P t=105",
            "T|p_ifelse|P t=105",
            "T|p_next|F t=105",
            "T|p_disable|P t=105",
            "T|cov2|C t=105",
            "T|cov2|C t=105",
            "T|p_range|P t=105",
            "T|p_range|P t=105",
            "T|p_fm|P t=105",
            "T|p_fm|P t=105",
            "T|p_impl_ov|F t=105",
            "T|p_nonc|P t=105",
            "T|p_within|P t=105",
            "T|p_within|P t=105",
            "T|p_within|P t=105",
            "T|p_rep_range|F t=105",
            "T|p_rep_range|P t=105",
            "T|p_and|F t=105",
            "T|p_and|P t=105",
            "T|p_not|F t=105",
            "T|p_iff|F t=105",
            "T|p_goto|F t=115",
            "T|p_goto|F t=115",
            "T|p_goto|F t=115",
            "T|p_next|F t=115",
            "T|p_until|F t=115",
            "T|p_ifelse|P t=115",
            "T|p_throughout|F t=115",
            "T|p_throughout|F t=115",
            "T|p_unb|P t=115",
            "T|p_unb|P t=115",
            "T|p_unb|P t=115",
            "T|p_unb|P t=115",
            "T|p_unb|P t=115",
            "T|p_unb|P t=115",
            "T|p_or|F t=115",
            "T|p_delay2|F t=115",
            "T|p_impl_nov|F t=115",
            "T|p_sev|P t=115",
            "T|p_sev|P t=115",
            "T|p_sev|P t=115",
            "T|p_sev|P t=115",
            "T|p_sev|P t=115",
            "T|p_sev|P t=115",
            "T|p_rep_range|F t=115",
            "T|p_rep_range|F t=115",
            "T|p_and|F t=115",
            "T|p_and|F t=115",
            "T|p_not|P t=115",
            "T|p_not|P t=115",
            "T|p_impl_ov|F t=125",
            "T|p_intersect|F t=125",
            "T|p_or|F t=125",
            "T|p_delay2|F t=125",
            "T|p_iff|F t=125",
            "T|p_next|P t=135",
            "T|p_ifelse|P t=135",
            "T|cov1|C t=135",
            "T|p_impl_nov|F t=135",
            "T|p_disable|F t=135",
            "T|p_range|F t=135",
            "T|p_fm|F t=135",
            "T|p_or|P t=135",
            "T|p_rep_range|F t=135",
            "T|p_and|F t=135",
            "T|p_not|P t=135",
            "T|p_not|P t=135",
            "T|p_iff|F t=135",
            "T|p_throughout|F t=145",
            "T|p_nonc|F t=145",
            "T|p_nonc|F t=145",
            "T|p_nonc|F t=145",
            "T|p_delay2|F t=145",
            "T|p_rep_range|F t=145",
            "T|p_and|F t=145",
            "T|p_and|F t=145",
            "T|p_not|P t=145",
            "T|p_iff|F t=145",
            "T|p_fm|P t=155",
            "T|p_range|P t=155",
            "T|p_rep|P t=155",
            "T|p_rep_range|F t=155",
            "T|p_rep_range|P t=155",
            "T|p_and|F t=155",
            "T|p_not|P t=155",
            "T|p_impl_ov|F t=165",
            "T|p_intersect|F t=165",
            "T|p_goto|P t=165",
            "T|p_goto|P t=165",
            "T|p_within|P t=165",
            "T|p_iff|F t=165",
            "T|p_impl_nov|F t=175",
            "T|p_intersect|F t=175",
            "T|p_throughout|F t=175",
            "T|p_throughout|F t=175",
            "T|p_ifelse|P t=175",
            "T|p_until|F t=175",
            "T|p_next|F t=175",
            "T|p_impl_ov|F t=175",
            "T|p_unb|P t=175",
            "T|p_unb|P t=175",
            "T|p_sev|P t=175",
            "T|p_sev|P t=175",
            "T|p_sev|P t=175",
            "T|p_rep_range|F t=175",
            "T|p_and|F t=175",
            "T|p_not|F t=175",
            "T|p_iff|F t=175",
            "T|p_impl_nov|F t=185",
            "T|p_delay2|F t=185",
            "T|p_or|P t=185",
            "T|p_or|F t=185",
            "T|p_ifelse|P t=185",
            "T|p_next|P t=185",
            "T|p_impl_ov|P t=185",
            "T|cov1|C t=185",
            "T|p_not|F t=185",
            "T|p_ifelse|F t=195",
            "T|p_fm|F t=195",
            "T|p_next|F t=195",
            "T|p_intersect|F t=195",
            "T|p_range|F t=195",
            "T|p_delay2|F t=195",
            "T|p_impl_nov|F t=195",
            "T|p_disable|F t=195",
            "T|p_rep_range|F t=195",
            "T|p_rep_range|F t=195",
            "T|p_rep_range|F t=195",
            "T|p_and|F t=195",
            "T|p_and|F t=195",
            "T|p_and|F t=195",
            "T|p_not|P t=195",
            "T|p_not|P t=195",
            "T|p_range|P t=205",
            "T|p_range|P t=205",
            "T|p_nonc|F t=205",
            "T|p_nonc|F t=205",
            "T|p_or|P t=205",
            "T|p_throughout|P t=205",
            "T|p_fm|P t=205",
            "T|p_fm|P t=205",
            "T|p_delay2|P t=205",
            "T|cov2|C t=205",
            "T|p_within|F t=205",
            "T|p_rep_range|F t=205",
            "T|p_and|F t=205",
            "T|p_not|P t=205",
            "T|p_iff|F t=205",
            "T|p_intersect|F t=215",
            "T|p_nonc|P t=215",
            "T|p_impl_ov|F t=215",
            "T|p_goto|P t=215",
            "T|p_goto|P t=215",
            "T|p_goto|P t=215",
            "T|p_within|P t=215",
            "T|p_within|P t=215",
            "T|p_iff|F t=215",
            "T|p_ifelse|P t=225",
            "T|p_next|P t=225",
            "T|p_or|P t=225",
            "T|p_disable|F t=225",
            "T|p_impl_nov|F t=225",
            "T|cov1|C t=225",
            "T|p_rep_range|F t=225",
            "T|p_and|F t=225",
            "T|p_not|P t=225",
            "T|p_not|P t=225",
            "T|p_iff|F t=225",
            "T|cov2|C t=235",
            "T|p_delay2|P t=235",
            "T|p_range|P t=235",
            "T|p_zero_rep|P t=235",
            "T|p_throughout|P t=235",
            "T|p_fm|P t=235",
            "T|p_rep_range|F t=235",
            "T|p_rep_range|P t=235",
            "T|p_and|F t=235",
            "T|p_and|P t=235",
            "T|p_not|P t=235",
            "T|p_goto|F t=245",
            "T|p_rep_range|F t=245",
            "T|p_and|F t=245",
            "T|p_not|P t=245",
            "T|p_within|F t=255",
            "T|p_rep_range|F t=255",
            "T|p_and|F t=255",
            "T|p_not|P t=255",
            "T|p_rep_range|F t=265",
            "T|p_and|F t=265",
            "T|p_not|P t=265",
            "T|p_rep_range|F t=275",
            "T|p_and|F t=275",
            "T|p_not|P t=275",
            "T|p_rep_range|F t=285",
            "T|p_and|F t=285",
            "T|p_not|P t=285",
            "T|p_rep_range|F t=295",
            "T|p_and|F t=295",
            "T|p_not|P t=295",
            "T|p_rep_range|F t=305",
            "T|p_and|F t=305",
            "T|p_not|P t=305",
            "T|p_rep_range|F t=315",
            "T|p_and|F t=315",
            "T|p_not|P t=315",
            "T|p_rep_range|F t=325",
            "T|p_and|F t=325",
            "T|p_not|P t=325",
            "T|p_sev|F t=330",
            "T|p_sev|F t=330",
        ],
        &[
            "T|p_iff|P t=5",
            "T|p_iff|F t=5",
            "T|p_iff|P t=25",
            "T|p_iff|F t=25",
            "T|p_iff|P t=45",
            "T|p_iff|F t=45",
            "T|p_iff|P t=65",
            "T|p_iff|F t=65",
            "T|p_iff|P t=95",
            "T|p_iff|F t=95",
            "T|p_iff|P t=115",
            "T|p_iff|F t=115",
            "T|p_iff|P t=155",
            "T|p_iff|F t=155",
            "T|p_iff|P t=185",
            "T|p_iff|F t=185",
            "T|p_iff|P t=195",
            "T|p_iff|F t=195",
            "T|p_iff|P t=235",
            "T|p_iff|F t=235",
            "T|p_iff|P t=245",
            "T|p_iff|F t=245",
            "T|p_iff|P t=255",
            "T|p_iff|F t=255",
            "T|p_iff|P t=265",
            "T|p_iff|F t=265",
            "T|p_iff|P t=275",
            "T|p_iff|F t=275",
            "T|p_iff|P t=285",
            "T|p_iff|F t=285",
            "T|p_iff|P t=295",
            "T|p_iff|F t=295",
            "T|p_iff|P t=305",
            "T|p_iff|F t=305",
            "T|p_iff|P t=315",
            "T|p_iff|F t=315",
            "T|p_iff|P t=325",
            "T|p_iff|F t=325",
            "T|p_until|P t=35",
            "T|p_until|P t=25",
            "T|p_until|P t=105",
            "T|p_until|P t=95",
            "T|p_until|P t=155",
            "T|p_until|P t=135",
            "T|p_until|F t=195",
            "T|p_until|P t=185",
            "T|p_until|P t=2",
            "T|p_zero_rep|P t=105",
            "T|p_zero_rep|P t=205",
        ],
    );
}

// §16.8, §16.12.1, §16.16: property declarations, triggered/matched, inferred clocks
#[test]
fn c16_assertions_misc() {
    // Known gap (§16.14.7): `16.14.7`: xezim misses 2 reference lines
    // Known gap (§16.13.6): `16.13.6`: xezim misses 3 reference lines
    // Assertions that complete in the same time step report from separate processes; IEEE 1800 §4.7 leaves their order open.
    check(
        "c16_misc2",
        include_str!("sv/c16_misc2.sv"),
        "c16_misc2",
        Order::Multiset,
        &[
            "T|16.12|param P t=25",
            "T|16.15|def P t=25",
            "T|16.14.3|cover prop t=25",
            "T|16.8|arg P t=35",
            "T|16.15|dis P t=35",
            "T|16.14.6|inf P t=35",
            "T|16.15|def P t=55",
            "T|16.12|param P t=55",
            "T|16.14.3|cover prop t=55",
            "T|16.15|dis P t=65",
            "T|16.8|arg P t=65",
            "T|16.14.6|inf P t=65",
            "T|16.14.3|cover prop t=95",
            "T|16.14.3|ncov=3",
        ],
        &["T|16.14.7|", "T|16.13.6|"],
    );
}

// §16.4.4, §16.12.17, §16.12.18: sequence methods, property operators, clocking-block properties
#[test]
fn c16_assertions_more() {
    // Known gap (§16.18): `16.18`: 3 reference lines differ from xezim's 9, e.g. reference `cb P t=25`, xezim `cb F t=5`
    // Assertions that complete in the same time step report from separate processes; IEEE 1800 §4.7 leaves their order open.
    check(
        "c16_more",
        include_str!("sv/c16_more.sv"),
        "c16_more",
        Order::Multiset,
        &[
            "T|16.9.3|sampled t=5 a=0 s=0",
            "T|16.9.3|sampled t=15 a=1 s=1",
            "T|16.11|match a t=15",
            "T|16.9.3|sampled t=25 a=0 s=0",
            "T|16.11|match b t=25",
            "T|16.9.3|sampled t=35 a=0 s=0",
            "T|16.12.18|typed P t=35",
            "T|16.9.3|sampled t=45 a=1 s=1",
            "T|16.11|match a t=45",
            "T|16.4.4|deferred F t=50",
            "T|16.9.3|sampled t=55 a=1 s=1",
            "T|16.11|match a t=55",
            "T|16.11|match b t=55",
            "T|16.9.3|sampled t=65 a=0 s=0",
            "T|16.12.18|typed P t=65",
            "T|16.11|match b t=65",
            "T|16.9.3|sampled t=75 a=0 s=0",
            "T|16.12.18|typed F t=75",
            "T|16.9.3|sampled t=85 a=1 s=1",
            "T|16.11|match a t=85",
            "T|16.9.3|sampled t=95 a=0 s=0",
            "T|16.18|cb F t=95",
        ],
        &[
            "T|16.18|cb P t=25",
            "T|16.18|cb F t=5",
            "T|16.18|cb P t=55",
            "T|16.18|cb F t=15",
            "T|16.18|cb P t=65",
            "T|16.18|cb F t=25",
            "T|16.18|cb F t=35",
            "T|16.18|cb F t=45",
            "T|16.18|cb F t=55",
            "T|16.18|cb F t=65",
            "T|16.18|cb F t=75",
            "T|16.18|cb F t=85",
        ],
    );
}
